In [ ]:
import pandas as pd

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Claire', 'David', 'Emma'],
    'Age': [25, 30, 22, 28, 35],
    'Salary USD': [50000, 60000, 45000, 70000, 80000],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing'],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female']
}

df = pd.DataFrame(data)

df

     Name  Age  Salary USD Department  Gender
0   Alice   25       50000         HR  Female
1     Bob   30       60000         IT    Male
2  Claire   22       45000    Finance  Female
3   David   28       70000         IT    Male
4    Emma   35       80000  Marketing  Female

## Preliminary exploration
Before deciding to look into a particular department or age group, it would helpful to know things like
- What are the different departments in this DataFrame?
- What's the range of ages in this DataFrame?

### `.unique()`

One way to see the distinct values in a column is to use `.unique()`. For readability, it is best to use this method on columns where you only expect a relatively small number of different values.

In [ ]:
df['Department'].unique()

array(['HR', 'IT', 'Finance', 'Marketing'], dtype=object)

### Ranges
For continuous numerical values, it might be more useful to know the range of available values. One way to accomplish this is to use `.max()` and `.min()`. Another could be to use `.describe()`, which provides information about the range as well as the quartiles.

In [ ]:
print(df['Age'].min(), df['Age'].max())

22 35

In [ ]:
df['Age'].describe()

count     5.000000
mean     28.000000
std       4.949747
min      22.000000
25%      25.000000
50%      28.000000
75%      30.000000
max      35.000000
Name: Age, dtype: float64

## Boolean indexing

Boolean indexing allows you to filter and select data based on specific conditions. The first step is to create a boolean mask (a Series of `True` and `False`). This mask then acts as a sort of filter to return rows that line up with `True` in the Series.

### Single condition

Let's say you want to know about those people in your DataFrame older than 29 years of age.

You can start by formalising the condition:

In [ ]:
df['Age'] > 29

0    False
1     True
2    False
3    False
4     True
Name: Age, dtype: bool

Comparing the output to 'df', you can see that for every row where the listed age is over 29, the above Series contains the value `True`.

This Series can then be used inside `.loc` to select rows. Since `df` and the Series have the same index, this technique returns all rows aligned to `True` values.

In [ ]:
df.loc[df['Age'] > 29,:]

   Name  Age  Salary USD Department  Gender
1   Bob   30       60000         IT    Male
4  Emma   35       80000  Marketing  Female

Logical conditions can become long and messy for some tasks, so it is sometimes a good practice to save the boolean mask as a separate variable and pass this variable to `.loc`.

In [ ]:
age_mask = df['Age'] > 29

In [ ]:
df.loc[age_mask,:]

   Name  Age  Salary USD Department  Gender
1   Bob   30       60000         IT    Male
4  Emma   35       80000  Marketing  Female

In [ ]:
department_mask = df['Department'] == "IT"

In [ ]:
df.loc[department_mask,:]

    Name  Age  Salary USD Department Gender
1    Bob   30       60000         IT   Male
3  David   28       70000         IT   Male

### Multiple conditions

Conditions can be combined using logical operators:
* **|** for OR,
* **&** for AND
* **~** for NOT.

When typing conditions in full, these must be grouped by using parentheses. Named variables, on the other hand, need not be enclosed.

In [ ]:
df.loc[ (df['Age'] > 29) & (df['Department']== "IT") , :]

  Name  Age  Salary USD Department Gender
1  Bob   30       60000         IT   Male

In [ ]:
df.loc[age_mask & department_mask, :]

NameError: name 'department_mask' is not defined

## Pandas filtering methods

Pandas also provides several methods which return boolean masks, and thus can be used in combination with `.loc` to filter DataFrames.

### .isin()
Used to compare a Series or DataFrame against a given collection, this method will return `True` for each value compared if the value is contained in the collection.     
We will most often use this to compare a single column (Series) of a DataFrame to a given list.

In [ ]:
df['Name'].isin(["Alice","David"])

0     True
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

In [ ]:
alice_david_mask = df['Name'].isin(["Alice","David"])

In [ ]:
df.loc[alice_david_mask,:]

    Name  Age  Salary USD Department  Gender
0  Alice   25       50000         HR  Female
3  David   28       70000         IT    Male

### .between()
Used to evaluate a Series, `.between()` returns `True` on any row whose value lies in the range of the two given arguments.        
By default, results will be inclusive of the two boundary values.

In [ ]:
df['Age'].between(25,30)

0     True
1     True
2    False
3     True
4    False
Name: Age, dtype: bool

In [ ]:
df.loc[df['Age'].between(25,30),:]

    Name  Age  Salary USD Department  Gender
0  Alice   25       50000         HR  Female
1    Bob   30       60000         IT    Male
3  David   28       70000         IT    Male

In [ ]:
df.loc[df['Name'].between("Bella","Daniel"),:]

     Name  Age  Salary USD Department  Gender
1     Bob   30       60000         IT    Male
2  Claire   22       45000    Finance  Female

### .nlargest() and .nsmallest()
Capable of filtering and sorting all at once, these methods return the `n` rows containing the largest or smallest values in a specified column or columns.

In [ ]:
df.nlargest(3,columns="Salary USD")

    Name  Age  Salary USD Department  Gender
4   Emma   35       80000  Marketing  Female
3  David   28       70000         IT    Male
1    Bob   30       60000         IT    Male

In [ ]:
df.nsmallest(5,columns="Age")

     Name  Age  Salary USD Department  Gender
2  Claire   22       45000    Finance  Female
0   Alice   25       50000         HR  Female
3   David   28       70000         IT    Male
1     Bob   30       60000         IT    Male
4    Emma   35       80000  Marketing  Female

In [ ]:
cities_df.query("Area_sq_miles >= 100 and Area_sq_miles <= 300")

      City  Population  Area_sq_miles Country  Year_Founded
2  Chicago     2716000          227.3     USA          1833