## Challenges

In [ ]:
data = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco', 'London', 'Paris', 'Berlin', 'Rome', 'Tokyo'],
    'Country': ['USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'France', 'Germany', 'Italy', 'Japan'],
    'Population (Millions)': [8.4, 3.9, 2.7, 2.3, 0.9, 8.9, 2.1, 3.7, 2.8, 13.9],
    'Area (km2)': [468.9, 502.8, 227.6, 1, 121.4, 1572, 105.4, 891.8, 1285, 2187],
    'Language': ['English', 'English', 'English', 'English', 'English', 'English', 'French', 'German', 'Italian', 'Japanese'],
    'Currency': ['USD', 'USD', 'USD', 'USD', 'USD', 'GBP', 'EUR', 'EUR', 'EUR', 'JPY'],
    'Continent': ['North America', 'North America', 'North America', 'North America', 'North America', 'Europe', 'Europe', 'Europe', 'Europe', 'Asia'],
    'Is_Capital': [False, False, False, False, False, True, True, True, True, True]
}

cities_df = pd.DataFrame(data)

# Adding more rows
extra_data = {
    'City': ['Sydney', 'Seoul', 'Beijing', 'Moscow', 'Cairo', 'Mumbai'],
    'Country': ['Australia', 'South Korea', 'China', 'Russia', 'Egypt', 'India'],
    'Population (Millions)': [5.3, 9.7, 21.5, 12.5, 9.5, 20.7],
    'Area (km2)': [1687, 605, 16411, 2561, 3034, 603],
    'Language': ['English', 'Korean', 'Mandarin', 'Russian', 'Arabic', 'Hindi'],
    'Currency': ['AUD', 'KRW', 'CNY', 'RUB', 'EGP', 'INR'],
    'Continent': ['Australia', 'Asia', 'Asia', 'Europe', 'Africa', 'Asia'],
    'Is_Capital': [False, True, True, True, True, False]
}

extra_df = pd.DataFrame(extra_data)
cities_df = pd.concat([cities_df, extra_df], ignore_index=True)

cities_df

,City,Country,Population (Millions),Area (km2),Language,Currency,Continent,Is_Capital
0,New York,USA,8.4,468.9,English,USD,North America,False
1,Los Angeles,USA,3.9,502.8,English,USD,North America,False
2,Chicago,USA,2.7,227.6,English,USD,North America,False
3,Houston,USA,2.3,1.0,English,USD,North America,False
4,San Francisco,USA,0.9,121.4,English,USD,North America,False
5,London,UK,8.9,1572.0,English,GBP,Europe,True
6,Paris,France,2.1,105.4,French,EUR,Europe,True
7,Berlin,Germany,3.7,891.8,German,EUR,Europe,True
8,Rome,Italy,2.8,1285.0,Italian,EUR,Europe,True
9,Tokyo,Japan,13.9,2187.0,Japanese,JPY,Asia,True
10,Sydney,Australia,5.3,1687.0,English,AUD,Australia,False
11,Seoul,South Korea,9.7,605.0,Korean,KRW,Asia,True
12,Beijing,China,21.5,16411.0,Mandarin,CNY,Asia,True
13,Moscow,Russia,12.5,2561.0,Russian,RUB,Europe,True
14,Cairo,Egypt,9.5,3034.0,Arabic,EGP,Africa,True
15,Mumbai,India,20.7,603.0,Hindi,INR,Asia,False

### Challenge 1
Create a new column 'City_Length' that contains the length of each city name

In [ ]:
cities_df['City_Length'] = cities_df['City'].str.len()
cities_df

### Challenge 2
Convert the 'City' names to uppercase and store them in a new column 'City_Upper'

In [ ]:
cities_df['City_Upper'] = cities_df['City'].str.upper()
cities_df

,City,Country,Population (Millions),Area (km2),Language,Currency,Continent,Is_Capital,City_Length,City_Upper
0,New York,USA,8.4,468.9,English,USD,North America,False,8,NEW YORK
1,Los Angeles,USA,3.9,502.8,English,USD,North America,False,11,LOS ANGELES
2,Chicago,USA,2.7,227.6,English,USD,North America,False,7,CHICAGO
3,Houston,USA,2.3,1.0,English,USD,North America,False,7,HOUSTON
4,San Francisco,USA,0.9,121.4,English,USD,North America,False,13,SAN FRANCISCO
5,London,UK,8.9,1572.0,English,GBP,Europe,True,6,LONDON
6,Paris,France,2.1,105.4,French,EUR,Europe,True,5,PARIS
7,Berlin,Germany,3.7,891.8,German,EUR,Europe,True,6,BERLIN
8,Rome,Italy,2.8,1285.0,Italian,EUR,Europe,True,4,ROME
9,Tokyo,Japan,13.9,2187.0,Japanese,JPY,Asia,True,5,TOKYO
10,Sydney,Australia,5.3,1687.0,English,AUD,Australia,False,6,SYDNEY
11,Seoul,South Korea,9.7,605.0,Korean,KRW,Asia,True,5,SEOUL
12,Beijing,China,21.5,16411.0,Mandarin,CNY,Asia,True,7,BEIJING
13,Moscow,Russia,12.5,2561.0,Russian,RUB,Europe,True,6,MOSCOW
14,Cairo,Egypt,9.5,3034.0,Arabic,EGP,Africa,True,5,CAIRO
15,Mumbai,India,20.7,603.0,Hindi,INR,Asia,False,6,MUMBAI

### Challenge 3
Check if the 'City' names end with the letter 'o'. Create a new column 'Ends_With_O' with the boolean results

In [ ]:
cities_df['Ends_With_O'] = cities_df['City'].str.endswith('o')
cities_df

### Challenge 4
Replace the word 'York' in 'City' names with 'Ville' and update the 'City' column accordingly

In [ ]:
cities_df['City'] = cities_df['City'].str.replace('York', 'Ville')
cities_df

,City,Country,Population (Millions),Area (km2),Language,Currency,Continent,Is_Capital,City_Length,City_Upper
0,New Ville,USA,8.4,468.9,English,USD,North America,False,8,NEW YORK
1,Los Angeles,USA,3.9,502.8,English,USD,North America,False,11,LOS ANGELES
2,Chicago,USA,2.7,227.6,English,USD,North America,False,7,CHICAGO
3,Houston,USA,2.3,1.0,English,USD,North America,False,7,HOUSTON
4,San Francisco,USA,0.9,121.4,English,USD,North America,False,13,SAN FRANCISCO
5,London,UK,8.9,1572.0,English,GBP,Europe,True,6,LONDON
6,Paris,France,2.1,105.4,French,EUR,Europe,True,5,PARIS
7,Berlin,Germany,3.7,891.8,German,EUR,Europe,True,6,BERLIN
8,Rome,Italy,2.8,1285.0,Italian,EUR,Europe,True,4,ROME
9,Tokyo,Japan,13.9,2187.0,Japanese,JPY,Asia,True,5,TOKYO
10,Sydney,Australia,5.3,1687.0,English,AUD,Australia,False,6,SYDNEY
11,Seoul,South Korea,9.7,605.0,Korean,KRW,Asia,True,5,SEOUL
12,Beijing,China,21.5,16411.0,Mandarin,CNY,Asia,True,7,BEIJING
13,Moscow,Russia,12.5,2561.0,Russian,RUB,Europe,True,6,MOSCOW
14,Cairo,Egypt,9.5,3034.0,Arabic,EGP,Africa,True,5,CAIRO
15,Mumbai,India,20.7,603.0,Hindi,INR,Asia,False,6,MUMBAI

### Challenge 5
Create a new column 'Country_Code' by extracting the first three characters from the 'Country' names

In [ ]:
cities_df['Country_Code'] = cities_df['Country'].str[:3]
cities_df

### Challenge 6
Count the occurrences of the letter 'a' in each 'City' name

In [ ]:
Count the occurrences of the letter 'a' in each 'City' name

In [ ]:
cities_df['City'].str.count('a')
cities_df

### Challenge 7
Check if the 'City' names start with the letter 'C' and end with the letter 'o'

In [ ]:
cities_df['City'].str.startswith('C') & cities_df['City'].str.endswith('o')
cities_df

,City,Country,Population (Millions),Area (km2),Language,Currency,Continent,Is_Capital,City_Length,City_Upper
0,New Ville,USA,8.4,468.9,English,USD,North America,False,8,NEW YORK
1,Los Angeles,USA,3.9,502.8,English,USD,North America,False,11,LOS ANGELES
2,Chicago,USA,2.7,227.6,English,USD,North America,False,7,CHICAGO
3,Houston,USA,2.3,1.0,English,USD,North America,False,7,HOUSTON
4,San Francisco,USA,0.9,121.4,English,USD,North America,False,13,SAN FRANCISCO
5,London,UK,8.9,1572.0,English,GBP,Europe,True,6,LONDON
6,Paris,France,2.1,105.4,French,EUR,Europe,True,5,PARIS
7,Berlin,Germany,3.7,891.8,German,EUR,Europe,True,6,BERLIN
8,Rome,Italy,2.8,1285.0,Italian,EUR,Europe,True,4,ROME
9,Tokyo,Japan,13.9,2187.0,Japanese,JPY,Asia,True,5,TOKYO
10,Sydney,Australia,5.3,1687.0,English,AUD,Australia,False,6,SYDNEY
11,Seoul,South Korea,9.7,605.0,Korean,KRW,Asia,True,5,SEOUL
12,Beijing,China,21.5,16411.0,Mandarin,CNY,Asia,True,7,BEIJING
13,Moscow,Russia,12.5,2561.0,Russian,RUB,Europe,True,6,MOSCOW
14,Cairo,Egypt,9.5,3034.0,Arabic,EGP,Africa,True,5,CAIRO
15,Mumbai,India,20.7,603.0,Hindi,INR,Asia,False,6,MUMBAI

### Challenge 8
Check if the 'City' names contain exactly two words

In [ ]:
Check if the 'City' names contain exactly two words

In [ ]:
cities_df['City'].str.split().str.len() == 2