# Challenges

In [ ]:
import pandas as pd
data = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco','London', 'Boston'],
    'Population': [8622698, 3990456, 2716000, 2312717, 870887, 8982000, 675647],
    'Area_sq_miles': [302.6, 468.7, 227.3, 627.8, 46.9, 607.0, 89.6],
    'Country': ['USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'USA'],
    'Year_Founded': [1624, 1781, 1833, 1836, 1776, 43, 1625]
}
cities_df = pd.DataFrame(data)
cities_df

            City  Population  Area_sq_miles Country  Year_Founded
0       New York     8622698          302.6     USA          1624
1    Los Angeles     3990456          468.7     USA          1781
2        Chicago     2716000          227.3     USA          1833
3        Houston     2312717          627.8     USA          1836
4  San Francisco      870887           46.9     USA          1776
5         London     8982000          607.0      UK            43
6         Boston      675647           89.6     USA          1625

### Challenge 1
Select all cities with a population greater than 2 million.

In [ ]:
cities_df[cities_df['Population'] > 2_000_000]

          City  Population  Area_sq_miles Country  Year_Founded
0     New York     8622698          302.6     USA          1624
1  Los Angeles     3990456          468.7     USA          1781
2      Chicago     2716000          227.3     USA          1833
3      Houston     2312717          627.8     USA          1836
5       London     8982000          607.0      UK            43

### Challenge 2
Select the 'City' and 'Area_sq_miles' columns for cities with an area greater than 300 square miles.

In [ ]:
cities_df.loc[cities_df['Area_sq_miles'] > 300, ['City', 'Area_sq_miles']]

          City  Area_sq_miles
0     New York          302.6
1  Los Angeles          468.7
3      Houston          627.8
5       London          607.0

### Challenge 3
Select the 'City', 'Area_sq_miles', and 'Year_Founded' columns for cities with a population less than 1 million or an area less than 500 square miles.

In [ ]:
cities_df.loc[
    (cities_df['Population'] < 1_000_000) | (cities_df['Area_sq_miles'] < 500),
    ['City', 'Area_sq_miles', 'Year_Founded']
]

            City  Area_sq_miles  Year_Founded
0       New York          302.6          1624
1    Los Angeles          468.7          1781
2        Chicago          227.3          1833
4  San Francisco           46.9          1776
6         Boston           89.6          1625

### Challenge 4
Using `.nlargest()`, select the 'City', 'Population', and 'Area_sq_miles' columns for the top 3 largest cities by population.

In [ ]:
cities_df.nlargest(3, 'Population')[['City', 'Population', 'Area_sq_miles']]

          City  Population  Area_sq_miles
5       London     8982000          607.0
0     New York     8622698          302.6
1  Los Angeles     3990456          468.7

### Challenge 5
Using `.isin()`, select the 'City', 'Population', and 'Year_Founded' columns for the cities San Francisco and Boston.

In [ ]:
cities_df.loc[
    cities_df['City'].isin(['San Francisco', 'Boston']),
    ['City', 'Population', 'Year_Founded']
]

            City  Population  Year_Founded
4  San Francisco      870887          1776
6         Boston      675647          1625

### Challenge 6
Select the 3 cities with smallest populations.

In [ ]:
cities_df.nsmallest(3, 'Population')

            City  Population  Area_sq_miles Country  Year_Founded
6         Boston      675647           89.6     USA          1625
4  San Francisco      870887           46.9     USA          1776
3        Houston     2312717          627.8     USA          1836

### Challenge 7
Using the ~ operator, select the 'City', 'Country', 'Population', and 'Area_sq_miles' columns for cities located outside the USA.

In [ ]:
cities_df.loc[
    ~cities_df['Country'].isin(['USA']),
    ['City', 'Country', 'Population', 'Area_sq_miles']
]

     City Country  Population  Area_sq_miles
5  London      UK     8982000          607.0

# Bonus
## A note on method chaining and a different way to filter

`.query()` allows you to filter data using a logical expression as a string. Since this method does not require column names to take reference to `df`, complex conditions can be written more easily. On the other hand, referencing strings within strings requires careful attention to the mixing of double and single quotes.

In [ ]:
df.query("Department == 'IT'")

    Name  Age  Salary USD Department Gender
1    Bob   30       60000         IT   Male
3  David   28       70000         IT   Male

In [ ]:
df.query("Department == 'IT' & Age > 29")

  Name  Age  Salary USD Department Gender
1  Bob   30       60000         IT   Male

Because `.query()` does not require you to refer to a DataFrame by name, it can be used in-line with other methods which transform or select data.

As an example, we can select the four youngest employees and then filter for those making a certain salary:

In [ ]:
df.nsmallest(4, 'Age').query('Department == "IT"')

    Name  Age  Salary USD Department Gender
3  David   28       70000         IT   Male
1    Bob   30       60000         IT   Male

Since the argument of `.query()` is itself a string, there are some special cases you might consider:  
1. When refering to a column that has a whitespace in the name, enclose the column with a backtick (`)
2. When refering to variables, prefix the variable with @

In [ ]:
df.query(" `Salary USD` < 50000")

     Name  Age  Salary USD Department  Gender
2  Claire   22       45000    Finance  Female

In [ ]:
age_limit = 25

In [ ]:
df.query("Age > @age_limit")

    Name  Age  Salary USD Department  Gender
1    Bob   30       60000         IT    Male
3  David   28       70000         IT    Male
4   Emma   35       80000  Marketing  Female

### Challenge 8
Using `.query()`, select all cities with a population greater than 2 million and founded after the year 1800.

In [ ]:
cities_df.query("Population > 2_000_000 and Year_Founded > 1800")

      City  Population  Area_sq_miles Country  Year_Founded
2  Chicago     2716000          227.3     USA          1833
3  Houston     2312717          627.8     USA          1836

### Challenge 9
Using `.query()`, select all cities with an area between 100 and 300 square miles.

In [ ]:
cities_df.query("Area_sq_miles >= 100 and Area_sq_miles <= 300")

      City  Population  Area_sq_miles Country  Year_Founded
2  Chicago     2716000          227.3     USA          1833