## 1. Challenges

#### 1.1
You are given a dictionary containing information about fruits. Create a DataFrame from this dictionary and display it.

In [ ]:
fruit_data = {
    'Fruit': ['Apple', 'Banana', 'Orange', 'Grapes'],
    'Color': ['Red', 'Yellow', 'Orange', 'Purple'],
    'Taste': ['Sweet', 'Sweet', 'Sweet', 'Sweet'],
    'Price': [1.0, 0.5, 0.8, 2.5]
}

In [ ]:
import pandas as pd
df = pd . DataFrame(fruit_data)
print(df)

    Fruit   Color  Taste  Price
0   Apple     Red  Sweet    1.0
1  Banana  Yellow  Sweet    0.5
2  Orange  Orange  Sweet    0.8
3  Grapes  Purple  Sweet    2.5

#### 1.2.
You are given a list of lists containing information about cities. Each inner list represents the data for a single city: the city's **name**, **population**, and **country**.     
Create a DataFrame from this list of lists and display the result.

In [ ]:
city_data = [
    ['New York', 8175133, 'USA'],
    ['Tokyo', 13929286, 'Japan'],
    ['London', 8908081, 'UK'],
    ['Mumbai', 12442373, 'India']
]

In [ ]:
import pandas as pd
df = pd.DataFrame(city_data, columns=['City', 'Population', 'Country'])
df

       City  Population Country
0  New York     8175133     USA
1     Tokyo    13929286   Japan
2    London     8908081      UK
3    Mumbai    12442373   India

#### 1.3
Download the .csv file from this [link](https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv).   
Save the .csv file on your Google Drive.  
Following the instructions from section 1.4 of this notebook, create a DataFrame with this data.

In [ ]:
url = 'https://drive.google.com/file/d/1_S007Pkamv7S8nl3mILXlNC1GuW44dJt/view?usp=drive_link'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
df = pd.read_csv(path)

#### 1.4
Explore the DataFrame and Series (any column you wish) from the previous exercise using all the methods and attributes learned in this notebook (info, shape, describe, head, tail, columns, index).

In [ ]:
import pandas as pd
print (df)

    species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0
1    Adelie  Torgersen            39.5           17.4              186.0
2    Adelie  Torgersen            40.3           18.0              195.0
3    Adelie  Torgersen             NaN            NaN                NaN
4    Adelie  Torgersen            36.7           19.3              193.0
..      ...        ...             ...            ...                ...
339  Gentoo     Biscoe             NaN            NaN                NaN
340  Gentoo     Biscoe            46.8           14.3              215.0
341  Gentoo     Biscoe            50.4           15.7              222.0
342  Gentoo     Biscoe            45.2           14.8              212.0
343  Gentoo     Biscoe            49.9           16.1              213.0

     body_mass_g     sex
0         3750.0    MALE
1         3800.0  FEMALE
2         3250.0  FEMALE
3            NaN     NaN
4         3450.0  FEMALE
..           ...     ...
339          NaN     NaN
340       4850.0  FEMALE
341       5750.0    MALE
342       5200.0  FEMALE
343       5400.0    MALE

[344 rows x 7 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
df.shape[0]

344

In [ ]:
df.shape[1]

7

In [ ]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [ ]:
df.describe(percentiles = [1/3, 2/3, 3/4])

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
33.3%       40.800000      16.200000         192.000000  3700.000000
50%         44.450000      17.300000         197.000000  4050.000000
66.7%       46.733333      18.300000         209.333333  4550.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [ ]:
df.nunique()

species                3
island                 3
bill_length_mm       164
bill_depth_mm         80
flipper_length_mm     55
body_mass_g           94
sex                    2
dtype: int64

In [ ]:
df['sex'].value_counts()

sex
MALE      168
FEMALE    165
Name: count, dtype: int64

In [ ]:
df.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,FEMALE
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,MALE
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

In [ ]:
df.tail(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
df.sample(8)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
45,Adelie,Dream,39.6,18.8,190.0,4600.0,MALE
261,Gentoo,Biscoe,49.6,16.0,225.0,5700.0,MALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
220,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,FEMALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
308,Gentoo,Biscoe,47.5,14.0,212.0,4875.0,FEMALE
91,Adelie,Dream,41.1,18.1,205.0,4300.0,MALE
254,Gentoo,Biscoe,49.1,14.8,220.0,5150.0,FEMALE

In [ ]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=344, step=1)

In [ ]:
df.isnull()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
339,False,False,True,True,True,True,True
340,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64