## Challenges

In [ ]:
import pandas as pd
data = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco'],
    'Population': [8622698, 3990456, 2716000, 2312717, 870887],
    'Area_sq_miles': [302.6, 468.7, 227.3, 627.8, 46.9],
    'Country': ['USA', 'USA', 'USA', 'USA', 'USA'],
    'Year_Founded': [1624, 1781, 1833, 1836, 1776]
}
cities_df = pd.DataFrame(data)
cities_df

            City  Population  Area_sq_miles Country  Year_Founded
0       New York     8622698          302.6     USA          1624
1    Los Angeles     3990456          468.7     USA          1781
2        Chicago     2716000          227.3     USA          1833
3        Houston     2312717          627.8     USA          1836
4  San Francisco      870887           46.9     USA          1776

**Make sure to save all the changes in the challenges to the original dataframe `cities_df`**

### Challenge 1
 Set the 'City' column as the index

In [ ]:
cities_df = cities_df.set_index(['City'])

### Challenge 2
Restore the default index (Keep 'City' as a column)

In [ ]:
cities_df = cities_df.reset_index()

### Challenge 3
Using `.iloc`, select the last 2 rows

In [ ]:
cities_df.iloc[-2:]

            City  Population  Area_sq_miles Country  Year_Founded
3        Houston     2312717          627.8     USA          1836
4  San Francisco      870887           46.9     USA          1776

### Challenge 4
Using `.loc`, select all the rows but only the columns 'Population' and 'City'

In [ ]:
cities_df.loc[:, ['Population', 'City']]

   Population           City
0     8622698       New York
1     3990456    Los Angeles
2     2716000        Chicago
3     2312717        Houston
4      870887  San Francisco

### Challenge 5
 using `.loc`, select the columns 'Area_sq_miles' and 'Country' for the city 'Houston'

In [ ]:
cities_df.loc[3, ['Area_sq_miles', 'Country']]

Area_sq_miles    627.8
Country            USA
Name: 3, dtype: object

### Challenge 6
 using `.iloc`, select the first 3 rows and the columns 'City' and 'Year_Founded'

In [ ]:
cities_df.iloc[:3, [0,4]]

          City  Year_Founded
0     New York          1624
1  Los Angeles          1781
2      Chicago          1833